# Build Requirements:
# Hugo Extended: 0.152.2+
# Dart Sass: 1.87.0
# Node.js: 22+

baseURL = "https://www.technobunnies.com/"
languageCode = "en-us"
title = "Technobunnies"
description = "Harrie's blog and showcase website."
theme = "bloggin"
enableGitInfo = true
apiurl = ""
enableRobotsTXT = true
copyright = 'Â© 2025 Harrie Bickle'
ignoreLogs = ['warning-goldmark-raw-html']


[params]
  description = "Harrie's personal blog"
  images = ["share.png"]
  title = "winston hearn"
  hny = ""
  order = 0
  [params.author]
    name = 'winston hearn'

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    codeFences = true
    tabWidth = 2
    noClasses = false

[outputs]
  home = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']